# pylint: disable=unnecessary-pass
# pylint: disable=line-too-long
# pylint: disable=trailing-whitespace

"""
Performance tests for the Online Bookstore application (NFR-001).

This script uses Locust to simulate user interactions with key endpoints of the web app:
- Homepage (/)
- Cart page (/cart)
- Checkout page (/checkout)

Objectives:
- Verify homepage loads in ≤ 2 seconds (NFR001-01)
- Verify cart and checkout pages load in ≤ 3 seconds (NFR001-02, NFR001-03)
- Simulate concurrent access to assess system stability under load (NFR001-04)

Performance metrics are generated by the Locust load testing tool.
"""

from locust import HttpUser, task, between

class PerformanceTestUser(HttpUser):
    """
    Simulates a user performing typical read-only actions in the Online Bookstore.

    The user:
    - Waits between 1 and 2 seconds between tasks
    - Loads the homepage
    - Loads the cart page
    - Loads the checkout page

    Each task includes performance assertions based on non-functional requirement NFR-001.
    """
    wait_time = between(1, 2)

    @task
    def test_homepage_load_time(self):
        """
        Test NFR001-01: Verify homepage loads within 2 seconds.
        Fails the request if it exceeds the threshold.
        """
        with self.client.get("/", catch_response=True) as response:
            if response.elapsed.total_seconds() > 2:
                response.failure(f"Homepage took {response.elapsed.total_seconds():.2f} seconds to load.")
            else:
                response.success()

    @task
    def test_cart_page_load_time(self):
        """
        Test NFR001-02: Verify cart page loads within 3 seconds.
        """
        with self.client.get("/cart", catch_response=True) as response:
            if response.elapsed.total_seconds() > 3:
                response.failure(f"Cart took {response.elapsed.total_seconds():.2f} seconds to load.")
            else:
                response.success()

    def skipped_checkout_page_load_time(self):
        """
        Skipped: Checkout page is not yet implemented.
        """
        pass
